//! rstn-crypto -- Post-Quantum Cryptography
//!
//! All cryptographic primitives for Resistance Network (RSTN).
//! Every algorithm here must resist both Shor's and Grover's attacks.
//!
//! Active primitives:
//! - Keccak-512 (hash, 256-bit quantum security via Grover resistance)
//! - Dilithium3 (signatures, NIST FIPS 204, Category 2)
//! - PQ-VRF (leader election, Dilithium-based)
//! - PQ-noise (transport encryption, Kyber KEM + Dilithium)
//! - Hybrid signatures (Dilithium3 + Ed25519, dual verification)
//! - SPHINCS+ / SLH-DSA (FIPS 205, hash-based fallback)
//! - Stealth addresses (Kyber768 KEM, one-time addresses)
//! - Forward security (epoch-based key rotation, anti long-range)
//! - Quantum alarm (emergency key rotation on cryptographic break)
//! - Account abstraction (multi-sig, social recovery, scheme rotation)

pub mod forward_security;
pub mod quantum_alarm;
pub mod account_abstraction;

use serde::{Deserialize, Serialize};
use serde_big_array::BigArray;
use thiserror::Error;
use zeroize::Zeroize;

#[derive(Debug, Error)]
pub enum CryptoError {
    #[error("invalid signature")]
    InvalidSignature,
    #[error("invalid key length")]
    InvalidKeyLength,
    #[error("hash computation failed")]
    HashFailed,
    #[error("VRF verification failed")]
    VrfVerificationFailed,
    #[error("pqcrypto error: {0}")]
    PqCrypto(String),
}

// --- Keccak-512 Hash ---------------------------------------
// Grover-resistant: 512-bit output gives 256-bit quantum security.

pub const HASH_SIZE: usize = 64;

pub fn keccak512(data: &[u8]) -> [u8; HASH_SIZE] {
    use sha3::Keccak512;
    use sha3::Digest;
    let mut hasher = Keccak512::new();
    hasher.update(data);
    let result = hasher.finalize();
    let mut out = [0u8; HASH_SIZE];
    out.copy_from_slice(&result);
    out
}

// --- Dilithium3 Signatures (NIST FIPS 204) ------------------
// Category 2 security (128-bit post-quantum).
// Public key: 1,952 bytes. Secret key: 4,032 bytes. Signature: 3,309 bytes.
// These are the canonical FIPS 204 (ML-DSA-65) parameter sizes, matching
// @noble/post-quantum (wallet/SDK) and all conformant FIPS 204 implementations.

pub const SIG_SIZE: usize = 3309;
pub const PUBKEY_SIZE: usize = 1952;
pub const PRIVKEY_SIZE: usize = 4032;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Dilithium3PublicKey(
    #[serde(with = "BigArray")] pub [u8; PUBKEY_SIZE],
);

#[derive(Clone, Debug, Serialize, Deserialize, Zeroize)]
pub struct Dilithium3SecretKey(
    #[serde(with = "BigArray")] pub [u8; PRIVKEY_SIZE],
);

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Dilithium3Signature(
    #[serde(with = "BigArray")] pub [u8; SIG_SIZE],
);

/// Keypair generated by a validator or wallet.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Dilithium3Keypair {
    pub public: Dilithium3PublicKey,
    pub secret: Dilithium3SecretKey,
}

// --- Dilithium3 / ML-DSA-65 (NIST FIPS 204 standard) ----------
//
// We use the `fips204` crate, which implements the FINAL FIPS 204 standard
// (ML-DSA-65). Its wire sizes -- pk = 1952, sk = 4032, sig = 3309 -- are
// IDENTICAL to @noble/post-quantum (ml_dsa65) used by the wallet and SDK.
// This guarantees that signatures produced by the wallet verify on-chain,
// and signatures produced by the node verify in the wallet. The previous
// `pqc_dilithium` crate used the round-3 submission (sig = 3293), which is
// NOT wire-compatible with FIPS 204 -- wallet signatures failed node
// verification, breaking the entire BFT vote flow.

use fips204::ml_dsa_65 as mldsa65;
use fips204::traits::{SerDes, Signer, Verifier};

impl Dilithium3Keypair {
    /// Generate a new ML-DSA-65 (Dilithium3) keypair using the FIPS 204 standard.
    /// Stores the raw serialized public key (1952 B) and secret key (4032 B).
    pub fn generate() -> Self {
        let (pk, sk) = mldsa65::try_keygen().expect("ML-DSA-65 keygen must succeed");
        let public_arr = pk.into_bytes();
        let secret_arr = sk.into_bytes();
        Self {
            public: Dilithium3PublicKey(public_arr),
            secret: Dilithium3SecretKey(secret_arr),
        }
    }

    /// Sign a message with the secret key using ML-DSA-65 (FIPS 204).
    /// Produces a 3309-byte signature that verifies against the public key
    /// in any FIPS 204-conformant implementation (wallet, SDK, other nodes).
    pub fn sign(&self, message: &[u8]) -> Dilithium3Signature {
        // Deserialize the stored secret key into the fips204 PrivateKey struct.
        let sk = mldsa65::PrivateKey::try_from_bytes(self.secret.0)
            .expect("stored ML-DSA-65 secret key must deserialize");
        // try_sign uses deterministic signing (FIPS 204) with an empty context.
        let sig = sk.try_sign(message, &[]).expect("ML-DSA-65 sign must succeed");
        Dilithium3Signature(sig)
    }
}

/// Verify an ML-DSA-65 (FIPS 204) signature.
/// The signature (3309 B) and public key (1952 B) are the exact wire formats
/// shared with the wallet, so cross-implementation verification works.
pub fn verify_signature(
    pubkey: &Dilithium3PublicKey,
    message: &[u8],
    signature: &Dilithium3Signature,
) -> Result<(), CryptoError> {
    // Reject the all-zero placeholder signature (used for unsigned genesis blocks).
    if signature.0.iter().all(|&b| b == 0) {
        return Err(CryptoError::InvalidSignature);
    }
    // Deserialize the public key into the fips204 PublicKey struct.
    let pk = mldsa65::PublicKey::try_from_bytes(pubkey.0)
        .map_err(|_| CryptoError::InvalidSignature)?;
    // verify() returns bool (true = valid). Empty context matches sign().
    if pk.verify(message, &signature.0, &[]) {
        Ok(())
    } else {
        Err(CryptoError::InvalidSignature)
    }
}

// --- PQ-VRF (Verifiable Random Function) --------------------
// Used for leader election in BFT+DAG consensus.
//
// A VRF must be: deterministic (same input + secret -> same output),
// verifiable (anyone can verify the output was computed correctly),
// and unique (only the secret key holder can produce a valid proof).
//
// Our VRF construction (HMAC-based):
//   output = Keccak-512(secret_key || input)     -- deterministic
//   proof  = Dilithium3.sign(Keccak-512(input))  -- proves knowledge of secret key
//
// Verification: the verifier checks that the proof is a valid Dilithium3
// signature on Keccak-512(input), AND that the output equals
// Keccak-512(Keccak-512(input) || proof_bytes).
//
// This binds the output to the proof: an attacker cannot claim a different
// output because the output is derived from the proof itself. The proof
// can only be produced by the secret key holder (Dilithium3 unforgeability).

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct VrfOutput(
    #[serde(with = "BigArray")] pub [u8; 64],
);

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct VrfProof(
    #[serde(with = "BigArray")] pub [u8; SIG_SIZE],
); // Dilithium3 signature on the input hash

pub struct VrfKeypair {
    pub public: Dilithium3PublicKey,
    pub secret: Dilithium3SecretKey,
}

impl VrfKeypair {
    pub fn from_dilithium(keypair: &Dilithium3Keypair) -> Self {
        Self {
            public: keypair.public.clone(),
            secret: Dilithium3SecretKey(keypair.secret.0),
        }
    }

    /// Evaluate the VRF on an input (e.g., epoch + round number).
    /// Returns the random output + a proof of correctness.
    ///
    /// The output is: Keccak-512(input_hash || proof_bytes).
    /// The proof is a Dilithium3 signature on Keccak-512(input).
    /// Both output and proof are bound together -- the output is derived
    /// from the proof, so an attacker cannot substitute a different output.
    pub fn evaluate(&self, input: &[u8]) -> (VrfOutput, VrfProof) {
        let input_hash = keccak512(input);

        // Proof: sign the input hash with Dilithium3
        let kp = Dilithium3Keypair {
            public: self.public.clone(),
            secret: Dilithium3SecretKey(self.secret.0),
        };
        let sig = kp.sign(&input_hash);
        let proof = VrfProof(sig.0.clone());

        // Output: derived from the proof -- Keccak-512(input_hash || proof_bytes)
        // This binds the output to the proof. Only the secret key holder can
        // produce a valid proof, and the output is deterministic given the proof.
        let output = keccak512(&[&input_hash[..], &sig.0[..]].concat());

        (VrfOutput(output), proof)
    }
}

/// Verify a VRF proof against a public key.
///
/// Two checks:
/// 1. The proof is a valid Dilithium3 signature on Keccak-512(input).
///    This proves the evaluator knew the secret key.
/// 2. The output matches Keccak-512(Keccak-512(input) || proof_bytes).
///    This binds the output to the proof -- an attacker cannot substitute
///    a different output because the output is derived from the proof.
///
/// If either check fails, verification fails.
pub fn verify_vrf(
    pubkey: &Dilithium3PublicKey,
    input: &[u8],
    output: &VrfOutput,
    proof: &VrfProof,
) -> Result<(), CryptoError> {
    let input_hash = keccak512(input);
    let sig = Dilithium3Signature(proof.0);

    // Check 1: verify the Dilithium3 signature on the input hash
    verify_signature(pubkey, &input_hash, &sig)?;

    // Check 2: verify the output is correctly derived from the proof
    // output = Keccak-512(input_hash || proof_bytes)
    let expected_output = keccak512(&[&input_hash[..], &proof.0[..]].concat());
    if output.0 != expected_output {
        return Err(CryptoError::VrfVerificationFailed);
    }

    Ok(())
}

// --- PQ-noise Transport -------------------------------------
// Post-quantum HYBRID handshake for P2P connections.
//
// Construction (Noise IK-inspired, post-quantum hybrid):
//   - Kyber768 KEM  (NIST FIPS 203 / ML-KEM-768) -- quantum-resistant key exchange
//   - X25519 ECDH   (RFC 7748)                    -- classical key exchange (defense in depth)
//   - Dilithium3    (NIST FIPS 204)               -- authentication / signatures
//   - HKDF-SHA3-512 (RFC 5869)                     -- key derivation from both secrets
//
// Hybrid security: the final shared secret is derived from BOTH the Kyber768
// KEM shared secret AND the X25519 ECDH shared secret. An attacker must break
// BOTH Kyber768 (lattice) AND X25519 (classical ECDH) to recover the session
// key. Against a quantum adversary that breaks X25519 (Shor), Kyber768 still
// holds. Against a future break of Kyber768, X25519 holds (pre-quantum).
//
// Message flow (initiator -> responder -> initiator):
//   1. Initiator: generate Kyber768 keypair + X25519 ephemeral keypair.
//      Send: Kyber768 public key || X25519 ephemeral public key || Dilithium3 sig.
//   2. Responder: encapsulate against the Kyber768 pubkey (-> ciphertext + KEM secret),
//      generate X25519 ephemeral keypair, DH(initiator_x25519_pub, responder_x25519_priv).
//      Send: Kyber768 ciphertext || X25519 ephemeral public key || Dilithium3 sig.
//   3. Initiator: decapsulate the Kyber768 ciphertext (-> KEM secret),
//      DH(responder_x25519_pub, initiator_x25519_priv).
//   4. Both derive: shared_secret = HKDF-Extract(salt, kem_secret || x25519_secret || transcript_hash)
//      then HKDF-Expand to a 32-byte session key.
//
// The shared secret is derived from SECRET material (KEM + ECDH), never from
// public keys. This is cryptographically sound for production use.

/// Kyber768 (ML-KEM-768) parameter sizes from pqc_kyber.
pub const KYBER_PUBKEY_SIZE: usize = 1184;
pub const KYBER_CIPHERTEXT_SIZE: usize = 1088;
pub const KYBER_SHARED_SECRET_SIZE: usize = 32;
pub const KYBER_SECRETKEY_SIZE: usize = 2400;

/// X25519 public key size (RFC 7748).
pub const X25519_PUBKEY_SIZE: usize = 32;

/// Role in the handshake.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum HandshakeRole {
    Initiator,
    Responder,
}

/// A Kyber768 keypair for the KEM (encapsulation key / decapsulation key).
pub struct Kyber768Keypair {
    pub public: Kyber768PublicKey,
    pub secret: Kyber768SecretKey,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Kyber768PublicKey(
    #[serde(with = "BigArray")] pub [u8; KYBER_PUBKEY_SIZE],
);

#[derive(Clone, Zeroize, Serialize, Deserialize)]
pub struct Kyber768SecretKey(
    #[serde(with = "BigArray")] pub [u8; KYBER_SECRETKEY_SIZE], // decap key
);

/// Encapsulated ciphertext produced by the responder.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct KyberCiphertext(
    #[serde(with = "BigArray")] pub [u8; KYBER_CIPHERTEXT_SIZE],
);

impl Kyber768Keypair {
    /// Generate a fresh Kyber768 KEM keypair using pure-Rust pqc_kyber.
    pub fn generate() -> Self {
        use rand_core::OsRng;
        let mut rng = OsRng;
        let keys = pqc_kyber::keypair(&mut rng).expect("Kyber768 keypair generation");
        Self {
            public: Kyber768PublicKey(keys.public),
            secret: Kyber768SecretKey(keys.secret),
        }
    }
}

/// Encapsulate a shared secret against a Kyber768 public key.
/// Returns (ciphertext, shared_secret). Used by the responder.
pub fn kyber_encapsulate(pk: &Kyber768PublicKey) -> (KyberCiphertext, [u8; KYBER_SHARED_SECRET_SIZE]) {
    use rand_core::OsRng;
    let mut rng = OsRng;
    let (ct, ss) = pqc_kyber::encapsulate(&pk.0, &mut rng).expect("Kyber768 encapsulation");
    (KyberCiphertext(ct), ss)
}

/// Decapsulate a Kyber768 ciphertext with a secret key.
/// Returns the shared secret. Used by the initiator.
pub fn kyber_decapsulate(
    sk: &Kyber768SecretKey,
    ct: &KyberCiphertext,
) -> Result<[u8; KYBER_SHARED_SECRET_SIZE], CryptoError> {
    pqc_kyber::decapsulate(&ct.0, &sk.0)
        .map_err(|e| CryptoError::PqCrypto(format!("{:?}", e)))
}

/// HKDF-SHA3-512 extract+expand into a 32-byte session key.
/// `ikm` = KEM shared secret || X25519 shared secret || transcript hash.
fn hkdf_session_key(salt: &[u8], ikm: &[u8]) -> [u8; 32] {
    use sha3::Sha3_512;
    use hkdf::Hkdf;
    let hk = Hkdf::<Sha3_512>::new(Some(salt), ikm);
    let mut okm = [0u8; 32];
    hk.expand(b"rstn-pq-noise-v1", &mut okm)
        .expect("HKDF expand to 32 bytes always succeeds");
    okm
}

/// Post-quantum hybrid noise handshake state.
///
/// Wire format (all lengths fixed, length-prefixed where noted):
///   initiator_msg  = kyber_pubkey(1184) || x25519_pub(32) || dilithium_sig(3309)
///   responder_msg  = kyber_ct(1088) || x25519_pub(32) || dilithium_sig(3309)
pub struct NoiseHandshake {
    pub role: HandshakeRole,
    /// Kyber768 KEM keypair (initiator holds decap key; responder encapsulates).
    pub kyber: Kyber768Keypair,
    /// X25519 ephemeral keypair for the classical half of the hybrid.
    pub x25519_secret: x25519_dalek::StaticSecret,
    /// Remote Dilithium3 static public key (for authentication).
    pub remote_static: Option<Dilithium3PublicKey>,
    /// The initiator's own Dilithium3 public key (set on the initiator side).
    /// The responder uses the caller-supplied `initiator_pub` to verify the
    /// initiator's signature -- this field is only populated on the initiator.
    pub initiator_pubkey: Option<Dilithium3PublicKey>,
    /// Derived 32-byte session key after handshake completion.
    pub shared_secret: Option<[u8; 32]>,
}

impl NoiseHandshake {
    /// Create a new handshake in the given role with a fresh Kyber768 + X25519 keypair.
    pub fn new(role: HandshakeRole) -> Self {
        use rand_core::OsRng;
        Self {
            role,
            kyber: Kyber768Keypair::generate(),
            x25519_secret: x25519_dalek::StaticSecret::random_from_rng(OsRng),
            remote_static: None,
            initiator_pubkey: None,
            shared_secret: None,
        }
    }

    /// Public X25519 ephemeral key to send on the wire.
    pub fn x25519_public(&self) -> x25519_dalek::PublicKey {
        x25519_dalek::PublicKey::from(&self.x25519_secret)
    }

    /// Initiate the PQ-noise handshake (initiator -> responder).
    ///
    /// Sends: Kyber768 public key || X25519 ephemeral public key || Dilithium3 signature
    /// over (kyber_pub || x25519_pub). The signature authenticates the initiator.
    ///
    /// SECURITY (C1): the initiator signs the transcript with its OWN long-term
    /// Dilithium3 identity keypair (`identity`), NOT a throwaway key. The
    /// responder must verify this signature against the initiator's expected
    /// public key -- otherwise a man-in-the-middle can substitute the Kyber/X25519
    /// keys and the responder has no way to detect it.
    pub fn initiate(&mut self, remote: &Dilithium3PublicKey, identity: &Dilithium3Keypair) -> Vec<u8> {
        self.remote_static = Some(remote.clone());
        // Stash the initiator identity so finalize() can verify the responder and
        // so the responder can be authenticated. (remote_static is the responder.)
        self.initiator_pubkey = Some(identity.public.clone());
        let x_pub = self.x25519_public();
        let mut transcript = Vec::with_capacity(KYBER_PUBKEY_SIZE + X25519_PUBKEY_SIZE);
        transcript.extend_from_slice(&self.kyber.public.0);
        transcript.extend_from_slice(x_pub.as_bytes());
        // Sign the transcript with our real Dilithium3 identity key.
        let sig = identity.sign(&transcript);
        let mut msg = Vec::with_capacity(transcript.len() + SIG_SIZE);
        msg.extend_from_slice(&transcript);
        msg.extend_from_slice(&sig.0);
        msg
    }

    /// Respond to an initiator message (responder -> initiator).
    ///
    /// Parses the initiator's Kyber768 pubkey + X25519 pubkey + signature,
    /// encapsulates a Kyber768 shared secret, performs X25519 ECDH, and
    /// derives the session key. Returns the responder's message.
    ///
    /// SECURITY (C1): `initiator_pub` is the initiator's expected Dilithium3
    /// public key. The responder verifies the initiator's signature against it
    /// BEFORE deriving the session key. This authenticates the initiator -- a
    /// man-in-the-middle without the initiator's Dilithium3 secret cannot
    /// produce a valid signature over the (kyber_pub || x25519_pub) transcript,
    /// so it cannot substitute the KEM/classical keys undetected.
    pub fn respond(
        &mut self,
        msg: &[u8],
        identity: &Dilithium3Keypair,
        initiator_pub: &Dilithium3PublicKey,
    ) -> Result<Vec<u8>, CryptoError> {
        let expected = KYBER_PUBKEY_SIZE + X25519_PUBKEY_SIZE + SIG_SIZE;
        if msg.len() < expected {
            return Err(CryptoError::InvalidKeyLength);
        }
        let mut kyber_pk = [0u8; KYBER_PUBKEY_SIZE];
        kyber_pk.copy_from_slice(&msg[..KYBER_PUBKEY_SIZE]);
        let mut x_remote = [0u8; X25519_PUBKEY_SIZE];
        x_remote.copy_from_slice(&msg[KYBER_PUBKEY_SIZE..KYBER_PUBKEY_SIZE + X25519_PUBKEY_SIZE]);
        let mut sig_arr = [0u8; SIG_SIZE];
        sig_arr.copy_from_slice(&msg[KYBER_PUBKEY_SIZE + X25519_PUBKEY_SIZE..expected]);

        // Verify the initiator's Dilithium3 signature over the transcript
        // (kyber_pub || x25519_pub) against the expected initiator public key.
        // This is the initiator-authentication half of the PQ-noise handshake.
        let mut init_transcript = Vec::with_capacity(KYBER_PUBKEY_SIZE + X25519_PUBKEY_SIZE);
        init_transcript.extend_from_slice(&kyber_pk);
        init_transcript.extend_from_slice(&x_remote);
        let init_sig = Dilithium3Signature(sig_arr);
        verify_signature(initiator_pub, &init_transcript, &init_sig)
            .map_err(|_| CryptoError::InvalidSignature)?;

        // Encapsulate Kyber768 against the initiator's public key.
        let (ct, kem_secret) = kyber_encapsulate(&Kyber768PublicKey(kyber_pk));

        // X25519 ECDH: responder_priv * initiator_pub
        let remote_x = x25519_dalek::PublicKey::from(x_remote);
        let x25519_secret = self.x25519_secret.diffie_hellman(&remote_x);

        // Build responder transcript: kyber_ct || x25519_pub
        let x_pub = self.x25519_public();
        let mut transcript = Vec::with_capacity(KYBER_CIPHERTEXT_SIZE + X25519_PUBKEY_SIZE);
        transcript.extend_from_slice(&ct.0);
        transcript.extend_from_slice(x_pub.as_bytes());

        // Sign transcript with our Dilithium3 identity key.
        let sig = identity.sign(&transcript);
        self.remote_static = Some(initiator_pub.clone());

        // Derive session key: HKDF(kem_secret || x25519_secret || transcript_hash)
        let transcript_hash = keccak512(&transcript);
        let mut ikm = Vec::with_capacity(KYBER_SHARED_SECRET_SIZE + 32 + HASH_SIZE);
        ikm.extend_from_slice(&kem_secret);
        ikm.extend_from_slice(x25519_secret.as_bytes());
        ikm.extend_from_slice(&transcript_hash);
        let salt = keccak512(&msg[..expected]);
        self.shared_secret = Some(hkdf_session_key(&salt, &ikm));

        let mut resp = Vec::with_capacity(transcript.len() + SIG_SIZE);
        resp.extend_from_slice(&transcript);
        resp.extend_from_slice(&sig.0);
        Ok(resp)
    }

    /// Finalize the handshake on the initiator side after receiving the responder's message.
    ///
    /// Decapsulates the Kyber768 ciphertext, performs X25519 ECDH, and derives
    /// the same session key as the responder.
    pub fn finalize(
        &mut self,
        resp: &[u8],
        _identity: &Dilithium3Keypair,
        init_msg: &[u8],
    ) -> Result<(), CryptoError> {
        let expected = KYBER_CIPHERTEXT_SIZE + X25519_PUBKEY_SIZE + SIG_SIZE;
        if resp.len() < expected {
            return Err(CryptoError::InvalidKeyLength);
        }
        let mut ct = [0u8; KYBER_CIPHERTEXT_SIZE];
        ct.copy_from_slice(&resp[..KYBER_CIPHERTEXT_SIZE]);
        let mut x_remote = [0u8; X25519_PUBKEY_SIZE];
        x_remote.copy_from_slice(&resp[KYBER_CIPHERTEXT_SIZE..KYBER_CIPHERTEXT_SIZE + X25519_PUBKEY_SIZE]);
        let mut sig_arr = [0u8; SIG_SIZE];
        sig_arr.copy_from_slice(&resp[KYBER_CIPHERTEXT_SIZE + X25519_PUBKEY_SIZE..expected]);

        // Decapsulate Kyber768 ciphertext -> KEM shared secret.
        let kem_secret = kyber_decapsulate(&self.kyber.secret, &KyberCiphertext(ct))?;

        // X25519 ECDH: initiator_priv * responder_pub
        let remote_x = x25519_dalek::PublicKey::from(x_remote);
        let x25519_secret = self.x25519_secret.diffie_hellman(&remote_x);

        // Reconstruct the same transcript the responder signed: kyber_ct || x25519_pub
        let mut transcript = Vec::with_capacity(KYBER_CIPHERTEXT_SIZE + X25519_PUBKEY_SIZE);
        transcript.extend_from_slice(&ct);
        transcript.extend_from_slice(&x_remote);

        // Verify the responder's Dilithium3 signature against the responder's static
        // public key, which the initiator learned during initiate() (self.remote_static).
        // This authenticates the responder -- a man-in-the-middle without the
        // responder's Dilithium3 secret key cannot produce a valid signature.
        let responder_pub = self
            .remote_static
            .clone()
            .ok_or(CryptoError::InvalidKeyLength)?;
        let sig = Dilithium3Signature(sig_arr);
        verify_signature(&responder_pub, &transcript, &sig)?;

        // Derive the same session key.
        let transcript_hash = keccak512(&transcript);
        let mut ikm = Vec::with_capacity(KYBER_SHARED_SECRET_SIZE + 32 + HASH_SIZE);
        ikm.extend_from_slice(&kem_secret);
        ikm.extend_from_slice(x25519_secret.as_bytes());
        ikm.extend_from_slice(&transcript_hash);
        let salt = keccak512(&init_msg[..KYBER_PUBKEY_SIZE + X25519_PUBKEY_SIZE + SIG_SIZE.min(init_msg.len())]);
        self.shared_secret = Some(hkdf_session_key(&salt, &ikm));
        Ok(())
    }

    /// Get the derived 32-byte session key after handshake completes.
    pub fn shared_secret(&self) -> Option<&[u8; 32]> {
        self.shared_secret.as_ref()
    }
}

// --- Hybrid Signatures (Dilithium3 + Ed25519) ----------------
// Dual verification: Every transaction & vote carries BOTH a post-quantum Dilithium3
// signature AND a classical Ed25519 signature. If either lattice or elliptic-curve
// cryptography is broken, the remaining scheme guarantees security.

pub const ED25519_PUBKEY_SIZE: usize = 32;
pub const ED25519_SIG_SIZE: usize = 64;
pub const HYBRID_SIG_SIZE: usize = SIG_SIZE + ED25519_SIG_SIZE; // 3309 + 64 = 3373 bytes
pub const HYBRID_PUBKEY_SIZE: usize = PUBKEY_SIZE + ED25519_PUBKEY_SIZE; // 1952 + 32 = 1984 bytes

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct HybridPublicKey {
    pub dilithium: Dilithium3PublicKey,
    pub ed25519: [u8; ED25519_PUBKEY_SIZE],
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct HybridSignature {
    pub dilithium: Dilithium3Signature,
    pub ed25519: [u8; ED25519_SIG_SIZE],
}

pub struct HybridKeypair {
    pub dilithium: Dilithium3Keypair,
    pub ed25519_signing: ed25519_dalek::SigningKey,
}

impl HybridKeypair {
    pub fn generate() -> Self {
        use rand_core::{OsRng, RngCore};
        let dilithium = Dilithium3Keypair::generate();
        // ed25519-dalek 3.x: SigningKey::generate() was removed. Generate 32
        // random bytes with OsRng and construct via from_bytes().
        let mut secret_bytes = [0u8; ED25519_PUBKEY_SIZE];
        OsRng.fill_bytes(&mut secret_bytes);
        let ed25519_signing = ed25519_dalek::SigningKey::from_bytes(&secret_bytes);
        Self {
            dilithium,
            ed25519_signing,
        }
    }

    pub fn public(&self) -> HybridPublicKey {
        HybridPublicKey {
            dilithium: self.dilithium.public.clone(),
            ed25519: self.ed25519_signing.verifying_key().to_bytes(),
        }
    }

    pub fn sign(&self, message: &[u8]) -> HybridSignature {
        use ed25519_dalek::Signer;
        let dilithium_sig = self.dilithium.sign(message);
        let ed_sig = self.ed25519_signing.sign(message);
        HybridSignature {
            dilithium: dilithium_sig,
            ed25519: ed_sig.to_bytes(),
        }
    }
}

pub fn verify_hybrid_signature(
    pubkey: &HybridPublicKey,
    message: &[u8],
    signature: &HybridSignature,
) -> Result<(), CryptoError> {
    // 1. Verify Post-Quantum Dilithium3 signature
    verify_signature(&pubkey.dilithium, message, &signature.dilithium)?;

    // 2. Verify Classical Ed25519 signature
    // ed25519-dalek 3.x: VerifyingKey::from_bytes and Signature::from_bytes
    // both return Result instead of infallible.
    use ed25519_dalek::Verifier;
    let ed_vk = ed25519_dalek::VerifyingKey::from_bytes(&pubkey.ed25519)
        .map_err(|_| CryptoError::InvalidSignature)?;
    let ed_sig = ed25519_dalek::Signature::from_bytes(&signature.ed25519);
    ed_vk.verify(message, &ed_sig)
        .map_err(|_| CryptoError::InvalidSignature)?;

    Ok(())
}

// --- SPHINCS+ / SLH-DSA Fallback (NIST FIPS 205 Standard) ----
// Hash-based post-quantum signature scheme acting as a fallback when activated
// by on-chain governance or quantum alarm. Hash-based signatures do not depend
// on lattice assumptions (Module-LWE).
//
// Uses the official RustCrypto `slh-dsa` crate implementing the FIPS-205 standard.
// Parameter set: Shake128f (Category 1 security, fast signatures).
// Public key: 32 bytes. Signature: 17,088 bytes.

pub const SPHINCS_PUBKEY_SIZE: usize = 32;
pub const SPHINCS_SIG_SIZE: usize = 17088;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SphincsPublicKey(
    #[serde(with = "BigArray")] pub [u8; SPHINCS_PUBKEY_SIZE],
);

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SphincsSignature(
    #[serde(with = "BigArray")] pub [u8; SPHINCS_SIG_SIZE],
);

pub struct SphincsKeypair {
    pub signing_key: slh_dsa::SigningKey<slh_dsa::Shake128f>,
}

impl SphincsKeypair {
    pub fn generate() -> Self {
        use rand_core::OsRng;
        let mut rng = OsRng;
        let signing_key = slh_dsa::SigningKey::<slh_dsa::Shake128f>::new(&mut rng);
        Self { signing_key }
    }

    pub fn public(&self) -> SphincsPublicKey {
        let vk = self.signing_key.verifying_key();
        let bytes = vk.to_bytes();
        let mut pk = [0u8; SPHINCS_PUBKEY_SIZE];
        pk.copy_from_slice(bytes.as_ref());
        SphincsPublicKey(pk)
    }

    /// Sign a message using official FIPS 205 / SLH-DSA (Shake128f).
    pub fn sign(&self, message: &[u8]) -> SphincsSignature {
        use rand_core::OsRng;
        use signature::RandomizedSigner;
        let mut rng = OsRng;
        let sig = self.signing_key.sign_with_rng(&mut rng, message);
        let sig_bytes = sig.to_bytes();
        let mut arr = [0u8; SPHINCS_SIG_SIZE];
        let copy_len = sig_bytes.as_ref().len().min(SPHINCS_SIG_SIZE);
        arr[..copy_len].copy_from_slice(&sig_bytes.as_ref()[..copy_len]);
        SphincsSignature(arr)
    }
}

/// Verifies SPHINCS+ / FIPS 205 signature integrity using real SLH-DSA verification.
pub fn verify_sphincs_signature(
    pubkey: &SphincsPublicKey,
    message: &[u8],
    signature: &SphincsSignature,
) -> Result<(), CryptoError> {
    use signature::Verifier;
    let vk = slh_dsa::VerifyingKey::<slh_dsa::Shake128f>::try_from(pubkey.0.as_ref())
        .map_err(|_| CryptoError::InvalidKeyLength)?;
    let sig = slh_dsa::Signature::<slh_dsa::Shake128f>::try_from(signature.0.as_ref())
        .map_err(|_| CryptoError::InvalidSignature)?;

    vk.verify(message, &sig)
        .map_err(|_| CryptoError::InvalidSignature)
}

// --- Stealth Addresses (Post-Quantum Kyber768 KEM) -----------
// One-time addresses derived via Kyber768 encapsulation. The recipient's public
// key is never exposed on-chain until the UTXO is spent. Prevents address reuse
// and protects public keys from quantum Shor attacks.

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StealthAddress {
    /// Derived 20-byte one-time address
    pub address: [u8; ADDRESS_SIZE],
    /// Kyber768 ciphertext required by recipient to recover the one-time private key
    pub ciphertext: KyberCiphertext,
}

pub fn generate_stealth_address(
    recipient_kyber_pk: &Kyber768PublicKey,
) -> StealthAddress {
    // Encapsulate a shared secret against recipient's Kyber768 pubkey
    let (ct, shared_secret) = kyber_encapsulate(recipient_kyber_pk);
    // One-time address derived from Keccak-512(shared_secret)
    let one_time_hash = keccak512(&[&shared_secret[..], b"rstn-stealth-v1"].concat());
    let mut addr = [0u8; ADDRESS_SIZE];
    addr.copy_from_slice(&one_time_hash[HASH_SIZE - ADDRESS_SIZE..]);
    StealthAddress {
        address: addr,
        ciphertext: ct,
    }
}

pub fn check_stealth_ownership(
    recipient_kyber_sk: &Kyber768SecretKey,
    stealth: &StealthAddress,
) -> bool {
    if let Ok(shared_secret) = kyber_decapsulate(recipient_kyber_sk, &stealth.ciphertext) {
        let expected_hash = keccak512(&[&shared_secret[..], b"rstn-stealth-v1"].concat());
        let expected_addr = &expected_hash[HASH_SIZE - ADDRESS_SIZE..];
        stealth.address == expected_addr
    } else {
        false
    }
}

// --- Address Derivation -------------------------------------

/// A RSTN address is the last 20 bytes of Keccak-512(pubkey).
pub const ADDRESS_SIZE: usize = 20;

pub fn derive_address(pubkey: &Dilithium3PublicKey) -> [u8; ADDRESS_SIZE] {
    let hash = keccak512(&pubkey.0);
    let mut addr = [0u8; ADDRESS_SIZE];
    addr.copy_from_slice(&hash[HASH_SIZE - ADDRESS_SIZE..]);
    addr
}

/// Format an address as a hex string with "rstn1" prefix.
/// Uses bech32-style encoding in production. For dev, hex is sufficient.
pub fn format_address(addr: &[u8; ADDRESS_SIZE]) -> String {
    let hex: String = addr.iter().map(|b| format!("{:02x}", b)).collect();
    format!("rstn1{}", hex) // Full 20-byte hex = 40 chars after prefix
}

// --- Tests -------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_keccak512_deterministic() {
        let input = b"hello rstn";
        let h1 = keccak512(input);
        let h2 = keccak512(input);
        assert_eq!(h1, h2);
        assert_eq!(h1.len(), 64);
    }

    #[test]
    fn test_keccak512_different_inputs() {
        let h1 = keccak512(b"input1");
        let h2 = keccak512(b"input2");
        assert_ne!(h1, h2);
    }

    #[test]
    fn test_keccak512_empty_input() {
        let h = keccak512(b"");
        assert_eq!(h.len(), 64);
        // Known Keccak-512 hash of empty input
        assert_eq!(h[0], 0x0e);
    }

    #[test]
    fn test_address_derivation_deterministic() {
        let pk = Dilithium3PublicKey([42u8; 1952]);
        let addr1 = derive_address(&pk);
        let addr2 = derive_address(&pk);
        assert_eq!(addr1, addr2);
        assert_eq!(addr1.len(), ADDRESS_SIZE);
    }

    #[test]
    fn test_different_pubkeys_different_addresses() {
        let pk1 = Dilithium3PublicKey([1u8; 1952]);
        let pk2 = Dilithium3PublicKey([2u8; 1952]);
        let addr1 = derive_address(&pk1);
        let addr2 = derive_address(&pk2);
        assert_ne!(addr1, addr2);
    }

    #[test]
    fn test_address_format() {
        let addr = [0xab; ADDRESS_SIZE];
        let formatted = format_address(&addr);
        assert!(formatted.starts_with("rstn1"));
        assert_eq!(formatted.len(), 6 + 40); // "rstn1" + 40 hex chars
    }

    #[test]
    fn test_keypair_generate_and_sign_verify() {
        let keypair = Dilithium3Keypair::generate();
        let msg = keccak512(b"test message");

        let sig = keypair.sign(&msg);
        assert_eq!(sig.0.len(), SIG_SIZE);

        // Verify with correct public key
        let result = verify_signature(&keypair.public, &msg, &sig);
        assert!(result.is_ok());
    }

    #[test]
    fn test_signature_rejects_wrong_message() {
        let keypair = Dilithium3Keypair::generate();
        let msg1 = keccak512(b"message 1");
        let msg2 = keccak512(b"message 2");

        let sig = keypair.sign(&msg1);
        let result = verify_signature(&keypair.public, &msg2, &sig);
        assert!(result.is_err());
    }

    #[test]
    fn test_signature_rejects_wrong_pubkey() {
        let keypair1 = Dilithium3Keypair::generate();
        let keypair2 = Dilithium3Keypair::generate();
        let msg = keccak512(b"test message");

        let sig = keypair1.sign(&msg);
        let result = verify_signature(&keypair2.public, &msg, &sig);
        assert!(result.is_err());
    }

    // -- VRF tests --

    #[test]
    fn test_vrf_evaluate_and_verify() {
        let keypair = Dilithium3Keypair::generate();
        let vrf_kp = VrfKeypair::from_dilithium(&keypair);
        let input = b"epoch_42_round_7";

        let (output, proof) = vrf_kp.evaluate(input);

        // Verification should succeed with correct pubkey + output + proof
        let result = verify_vrf(&keypair.public, input, &output, &proof);
        assert!(result.is_ok(), "VRF verification should succeed with valid output");
    }

    #[test]
    fn test_vrf_rejects_tampered_output() {
        let keypair = Dilithium3Keypair::generate();
        let vrf_kp = VrfKeypair::from_dilithium(&keypair);
        let input = b"epoch_42_round_7";

        let (mut output, proof) = vrf_kp.evaluate(input);

        // Tamper with the output -- flip a bit
        output.0[0] ^= 0x01;

        // Verification should FAIL -- output doesn't match proof
        let result = verify_vrf(&keypair.public, input, &output, &proof);
        assert!(result.is_err(), "VRF verification should fail with tampered output");
    }

    #[test]
    fn test_vrf_rejects_wrong_pubkey() {
        let keypair1 = Dilithium3Keypair::generate();
        let keypair2 = Dilithium3Keypair::generate();
        let vrf_kp = VrfKeypair::from_dilithium(&keypair1);
        let input = b"epoch_42_round_7";

        let (output, proof) = vrf_kp.evaluate(input);

        // Verification with wrong pubkey should fail
        let result = verify_vrf(&keypair2.public, input, &output, &proof);
        assert!(result.is_err(), "VRF verification should fail with wrong pubkey");
    }

    #[test]
    fn test_vrf_rejects_wrong_input() {
        let keypair = Dilithium3Keypair::generate();
        let vrf_kp = VrfKeypair::from_dilithium(&keypair);

        let (output, proof) = vrf_kp.evaluate(b"epoch_42_round_7");

        // Verify with different input -- should fail
        let result = verify_vrf(&keypair.public, b"epoch_42_round_8", &output, &proof);
        assert!(result.is_err(), "VRF verification should fail with wrong input");
    }

    // -- PQ-noise hybrid handshake tests --

    #[test]
    fn test_kyber768_keypair_sizes() {
        let kp = Kyber768Keypair::generate();
        assert_eq!(kp.public.0.len(), KYBER_PUBKEY_SIZE);
        // Decapsulation key is non-trivial in length.
        assert!(kp.secret.0.len() >= KYBER_SHARED_SECRET_SIZE);
    }

    #[test]
    fn test_kyber768_encapsulate_decapsulate_roundtrip() {
        let kp = Kyber768Keypair::generate();
        let (ct, ss_enc) = kyber_encapsulate(&kp.public);
        assert_eq!(ct.0.len(), KYBER_CIPHERTEXT_SIZE);
        assert_eq!(ss_enc.len(), KYBER_SHARED_SECRET_SIZE);

        let ss_dec = kyber_decapsulate(&kp.secret, &ct).expect("decapsulate succeeds");
        // The two parties must derive the SAME Kyber768 shared secret.
        assert_eq!(ss_enc, ss_dec, "Kyber768 KEM shared secrets must match");
    }

    #[test]
    fn test_kyber768_decapsulate_rejects_wrong_secret() {
        let kp1 = Kyber768Keypair::generate();
        let kp2 = Kyber768Keypair::generate();
        let (ct, _ss) = kyber_encapsulate(&kp1.public);
        // Decapsulating a ciphertext for kp1 with kp2's secret must fail or differ.
        let result = kyber_decapsulate(&kp2.secret, &ct);
        // Decapsulation with the wrong key either errors or yields a different secret.
        match result {
            Ok(ss) => assert_ne!(ss, _ss, "wrong-key decapsulation must not match"),
            Err(_) => { /* acceptable: decap rejected the ciphertext */ }
        }
    }

    #[test]
    fn test_pq_noise_handshake_shared_secret_matches() {
        // Two parties run the hybrid PQ-noise handshake and must agree on the
        // same 32-byte session key.
        let initiator_identity = Dilithium3Keypair::generate();
        let responder_identity = Dilithium3Keypair::generate();

        let mut initiator = NoiseHandshake::new(HandshakeRole::Initiator);
        let mut responder = NoiseHandshake::new(HandshakeRole::Responder);

        // 1. Initiator -> responder (signs with its real identity)
        let init_msg = initiator.initiate(&responder_identity.public, &initiator_identity);

        // 2. Responder verifies the initiator's signature + responds
        let resp_msg = responder
            .respond(&init_msg, &responder_identity, &initiator_identity.public)
            .expect("responder handshake succeeds");

        // 3. Initiator finalizes (verifies the responder's signature)
        initiator
            .finalize(&resp_msg, &initiator_identity, &init_msg)
            .expect("initiator finalize succeeds");

        // Both must derive the SAME session key from secret KEM + ECDH material.
        let i_secret = initiator.shared_secret().expect("initiator has secret");
        let r_secret = responder.shared_secret().expect("responder has secret");
        assert_eq!(i_secret, r_secret, "PQ-noise session keys must match");
        assert_ne!(i_secret, &[0u8; 32], "session key must be non-zero");
    }

    #[test]
    fn test_pq_noise_rejects_tampered_responder_message() {
        let initiator_identity = Dilithium3Keypair::generate();
        let responder_identity = Dilithium3Keypair::generate();

        let mut initiator = NoiseHandshake::new(HandshakeRole::Initiator);
        let mut responder = NoiseHandshake::new(HandshakeRole::Responder);

        let init_msg = initiator.initiate(&responder_identity.public, &initiator_identity);
        let mut resp_msg = responder
            .respond(&init_msg, &responder_identity, &initiator_identity.public)
            .expect("responder handshake succeeds");

        // Flip a bit in the responder's Dilithium3 signature (last 3309 bytes).
        let sig_start = resp_msg.len() - SIG_SIZE;
        resp_msg[sig_start] ^= 0x01;

        let result = initiator.finalize(&resp_msg, &initiator_identity, &init_msg);
        assert!(result.is_err(), "tampered responder signature must be rejected");
    }

    #[test]
    fn test_pq_noise_rejects_wrong_identity_on_finalize() {
        // Man-in-the-middle scenario: the initiator believes it is talking to
        // `wrong_identity` (so it pins that as remote_static during initiate()),
        // but the actual responder signs with `responder_identity`. The
        // signature verification in finalize() must reject this mismatch.
        let initiator_identity = Dilithium3Keypair::generate();
        let responder_identity = Dilithium3Keypair::generate();
        let wrong_identity = Dilithium3Keypair::generate();

        let mut initiator = NoiseHandshake::new(HandshakeRole::Initiator);
        let mut responder = NoiseHandshake::new(HandshakeRole::Responder);

        // Initiator pins the WRONG responder identity as remote_static.
        let init_msg = initiator.initiate(&wrong_identity.public, &initiator_identity);
        // The real responder answers with its own identity.
        let resp_msg = responder
            .respond(&init_msg, &responder_identity, &initiator_identity.public)
            .expect("responder handshake succeeds");

        // finalize() verifies the signature against remote_static (wrong_identity),
        // but the signature was produced by responder_identity -> must fail.
        let result = initiator.finalize(&resp_msg, &initiator_identity, &init_msg);
        assert!(result.is_err(), "wrong identity verification must fail");
    }

    #[test]
    fn test_pq_noise_rejects_wrong_initiator_identity_on_respond() {
        // C1: the responder must reject an initiator whose signature does not
        // match the expected initiator public key. A man-in-the-middle that
        // substitutes the Kyber/X25519 keys cannot forge the initiator's
        // Dilithium3 signature, so respond() must fail.
        let initiator_identity = Dilithium3Keypair::generate();
        let responder_identity = Dilithium3Keypair::generate();
        let attacker_identity = Dilithium3Keypair::generate();

        let mut attacker = NoiseHandshake::new(HandshakeRole::Initiator);
        let mut responder = NoiseHandshake::new(HandshakeRole::Responder);

        // The attacker initiates with its OWN identity (not the expected one).
        let init_msg = attacker.initiate(&responder_identity.public, &attacker_identity);

        // The responder expects the real initiator's public key, but the
        // signature was produced by the attacker -> must fail.
        let result = responder.respond(&init_msg, &responder_identity, &initiator_identity.public);
        assert!(result.is_err(), "responder must reject wrong initiator identity");
    }

    #[test]
    fn test_hybrid_signature_sign_and_verify() {
        let keypair = HybridKeypair::generate();
        let pubkey = keypair.public();
        let msg = b"hybrid signature test message";

        let sig = keypair.sign(msg);
        assert!(verify_hybrid_signature(&pubkey, msg, &sig).is_ok());

        // Tamper message -> fail
        assert!(verify_hybrid_signature(&pubkey, b"wrong message", &sig).is_err());

        // Tamper Ed25519 signature byte -> fail
        let mut bad_sig = sig.clone();
        bad_sig.ed25519[0] ^= 0xff;
        assert!(verify_hybrid_signature(&pubkey, msg, &bad_sig).is_err());
    }

    #[test]
    fn test_sphincs_signature_sign_and_verify() {
        let keypair = SphincsKeypair::generate();
        let msg = b"sphincs+ test message";
        let sig = keypair.sign(msg);
        assert_eq!(sig.0.len(), SPHINCS_SIG_SIZE);
        assert!(verify_sphincs_signature(&keypair.public, msg, &sig).is_ok());

        // Zero signature -> fail
        let zero_sig = SphincsSignature([0u8; SPHINCS_SIG_SIZE]);
        assert!(verify_sphincs_signature(&keypair.public, msg, &zero_sig).is_err());
    }

    #[test]
    fn test_stealth_address_generation_and_ownership() {
        let recipient_kyber = Kyber768Keypair::generate();
        let stealth = generate_stealth_address(&recipient_kyber.public);

        // Recipient can verify ownership
        assert!(check_stealth_ownership(&recipient_kyber.secret, &stealth));

        // Wrong recipient secret key fails ownership check
        let wrong_recipient = Kyber768Keypair::generate();
        assert!(!check_stealth_ownership(&wrong_recipient.secret, &stealth));
    }
}
